spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kopring?userUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    hikari:
      connection-timeout: 3000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
